### ISSUE TITLE
Почему purchase = paymentOrderBinding.do

### ISSUE THREAD

**Issue by CvekCoding** [AndrewNovikof/omnipay-sberbank#13]
Добрый вечер.
У меня вопрос: почему дефолтный метод `purchase`, который вроде как рекомендован для проведения платежа, у вас направлен на апи `paymentOrderBinding.do`. А то, что по-моему должно быть в `purchase`, у вас в `authorize`?

Или я чего-то недопонял?

Заранее благодарен.

**Comment by AndrewNovikof** [comment]
Добрый день.

Метод `authorize` блокирует сумму на счету клиента и их списание потом нужно подтвердить. Если это не сделать, бронь снимется автоматически через 2 недели.
Метод `purchase` используется для проведения платежа по [связкам](https://developer.sberbank.ru/doc/v1/acquiring/rest-desc-func)

**Comment by CvekCoding** [comment]
@AndrewNovikof странно, но в доке об этом не написано:
https://developer.sberbank.ru/doc/v1/acquiring/rest-requests1pay

Вот если [2-стадийная](https://developer.sberbank.ru/doc/v1/acquiring/rest-requests2pay), то там добавляется шаг `deposit`, который списывает. Но судя по доке, при 1-стадийной достаточно `authorize` вроде как.

**Comment by AndrewNovikof** [comment]
Эти методы - это интерфейс [omnipay](https://github.com/thephpleague/omnipay#gateway-methods), поэтому такая адаптация интерфейса сбербанка на интерфейс omnipay.

**Comment by AndrewNovikof** [comment]
Возможно нужно было сделать одностадийную на метод `purchase `. Но так уж сложилось)

**Comment by CvekCoding** [comment]
Ясно. Поиграюсь.
В любом случае спасибо за реп!
