### ISSUE TITLE
Обновить версию зависимости omnipay/common

### ISSUE THREAD

**Issue by andchir** [AndrewNovikof/omnipay-sberbank#14]
Пожалуйста, обновите версию зависимости.

Сейчас:
~~~
"omnipay/common": "v3.0.2"
~~~

Нужно:
~~~
"omnipay/common": "v3.0.3"
~~~
или:
~~~
"omnipay/common": "^v3.0.2"
~~~

В версии 3.0.3 добавили поддержку Symfony5, сейчас ваш пакет на Symfony5 не устанавливается.

**Comment by AndrewNovikof** [comment]
Привет!

Спасибо, пул-реквест влил в мастер:
https://github.com/AndrewNovikof/omnipay-sberbank/pull/15

**Comment by andchir** [comment]
Пожалуйста, сделайте релиз, чтобы пакет обновился на packagist.org.

**Comment by AndrewNovikof** [comment]
Да, совсем забыл, пардон.
