### ISSUE TITLE
Incompatible version with last Omnipay

### ISSUE THREAD

**Issue by idevin** [AndrewNovikof/omnipay-sberbank#18]
Is there php 8 support? 
and last omnipay doesn't supported with Your package

Problem 1
    - andrewnovikof/omnipay-sberbank[3.0.1, ..., 3.0.3] require omnipay/common v3.0-alpha.1 -> found omnipay/common[v3.0-alpha.1] but the package is fixed to v3.1.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - andrewnovikof/omnipay-sberbank 3.1.alpha.2 requires omnipay/common v3.0-alpha.2 -> found omnipay/common[v3.0-alpha.2] but the package is fixed to v3.1.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - andrewnovikof/omnipay-sberbank[3.2.0, ..., 3.2.2] require php ^7.1 -> your php version (8.0.7) does not satisfy that requirement.
    - Root composer.json requires andrewnovikof/omnipay-sberbank ^3.0 -> satisfiable by andrewnovikof/omnipay-sberbank[3.0.1, ..., 3.2.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by itdelta-prog** [comment]
Здравствуйте, при установке пакетов получаем следующую проблему

Problem 1
    - andrewnovikof/omnipay-sberbank 3.0.3 requires omnipay/common v3.0-alpha.1 -> satisfiable by omnipay/common[v3.0-alpha.1].
    - andrewnovikof/omnipay-sberbank 3.1.alpha.2 requires omnipay/common v3.0-alpha.2 -> satisfiable by omnipay/common[v3.0-alpha.2].
    - andrewnovikof/omnipay-sberbank[3.0.1, ..., 3.0.2] require php-http/guzzle6-adapter ^1.1 -> satisfiable by php-http/guzzle6-adapter[v1.1.0, v1.1.1].
    - omnipay/common v3.0-alpha.1 requires php ^5.6|^7 -> your php version (8.1.13) does not satisfy that requirement.
    - omnipay/common v3.0-alpha.2 requires php ^7.1 -> your php version (8.1.13) does not satisfy that requirement.
    - andrewnovikof/omnipay-sberbank[3.2.0, ..., 3.2.2] require php ^7.1 -> your php version (8.1.13) does not satisfy that requirement.
    - php-http/guzzle6-adapter[v1.1.0, ..., v1.1.1] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - Root composer.json requires andrewnovikof/omnipay-sberbank ^3.0 -> satisfiable by andrewnovikof/omnipay-sberbank[3.0.1, ..., 3.2.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require andrewnovikof/omnipay-sberbank:*" to figure out if any version is installable, or "composer require andrewnovikof/omnipay-sberbank:^2.1" if you know which you need.

Не могли бы вы обновиться до php ^8 и послденей версии omnipay?

**Comment by AndrewNovikof** [comment]
Привет! Спасибо за комментарий! Постараюсь сегодня сделать.

**Comment by AndrewNovikof** [comment]
fixed version
https://github.com/AndrewNovikof/omnipay-sberbank/tree/3.3.2
